name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Buld and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t diegwl/devops-nlw:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push diegwl/devops-nlw:${{ steps.generate_sha.outputs.sha }}
          docker tag diegwl/devops-nlw:${{ steps.generate_sha.outputs.sha }} diegwl/devops-nlw:latest
          docker push diegwl/devops-nlw:latest